services:
  api:
    container_name: car_api
    build:
      context: ./api
      dockerfile: src/CarAccessControl.API/Dockerfile
    environment:
      FrontEnd__url: ${WEB_PUBLIC_URL}
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__Default: Host=db;Port=5432;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
      ModelUrl: "${AI_SERVICE_URL}"
    ports:
      - "${API_PUBLIC_PORT}:8080"
    depends_on:
      - db
      - ai_model
    networks:
      - car_net

  web:
    container_name: car_web
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        VITE_BASE_URL: "${API_PUBLIC_URL}"
    ports:
      - "${WEB_PUBLIC_PORT}:80"
    depends_on:
      - api
    networks:
      - car_net

  db:
    image: postgres:18
    container_name: car_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    networks:
      - car_net

  ai_model:
    image: plate-recognition:0.0.1-warp-product
    container_name: car_ai_model
    networks:
      - car_net

networks:
  car_net:

volumes:
  pgdata: