services:
  api:
    container_name: car_api
    build:
      context: ./api
      dockerfile: src/CarAccessControl.API/Dockerfile
    environment:
      FrontEnd__url: http://localhost
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__Default: Host=db;Port=5432;Database=car_access_control;Username=postgres;Password=12345
      ModelUrl: "http://localhost:8000"
    ports:
      - "8080:8080"
    depends_on:
      - db
      - ai_model
    networks:
      - car_net

  web:
    container_name: car_web
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        VITE_BASE_URL: "http://localhost:8080"
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - car_net

  db:
    image: postgres:18
    container_name: car_db
    environment:
      POSTGRES_DB: car_access_control
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - car_net

  ai_model:
    image: plate-recognition:0.0.1-warp-product
    container_name: car_ai_model
    ports:
      - "8000:8000"
    networks:
      - car_net

networks:
  car_net:

volumes:
  pgdata: