services:
  car-access-api:
    image: car-access-control/api:v1
    container_name: car_api_container
    restart: always
    build:
      context: .
      dockerfile: src/CarAccessControl.API/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080